
version: '3'

services:

  shard2svr1:
    container_name: shard2svr1
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 24004:27017
    volumes:
      - shard2svr1:/data/db
    networks:
      - mongo

  shard2svr2:
    container_name: shard2svr2
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    volumes:
      - shard2svr2:/data/db
    networks:
      - mongo

  shard2svr3:
    container_name: shard2svr3
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    volumes:
      - shard2svr3:/data/db
    networks:
      - mongo

volumes:
  shard2svr1: {}
  shard2svr2: {}
  shard2svr3: {}

networks:
  mongo:
    name: mongo
    external: true
